name: DeepSketch2Wear
channels:
  - https://conda.anaconda.org/pytorch3d
  - https://conda.anaconda.org/anaconda
  - <unknown>
  - https://conda.anaconda.org/iopath
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - boost=1.74.0=py39h5472131_5
  - boost-cpp=1.74.0=hc6e9bd1_3
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2024.2.2=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cmake=3.3.1=0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=10.2.89=h8f6ccaa_8
  - eigen=3.4.0=h4bd325d_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.15=he1e5248_0
  - icu=68.2=h9c3ff4c_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - iopath=0.1.9=py39
  - jpeg=9b=0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.14=0
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.1.0=h2733197_1
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.0=h89dd481_0
  - lz4-c=1.9.4=h6a678d5_0
  - mesa-libglu-conda-x86_64=9.0.0=h80376cc_1108
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpfr=4.0.2=hb69a4c5_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.12=h7f8727e_0
  - pillow=9.3.0=py39hace64e9_1
  - pip=23.3.1=py39h06a4308_0
  - portalocker=2.8.2=py39hf3d152e_1
  - python=3.9.18=h955ad1f_0
  - python_abi=3.9=2_cp39
  - pytorch=1.13.0=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.5=py39_cu117_pyt1130
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_1
  - sqlite=3.41.2=h5eee18b_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.13.0=py39_cu117
  - torchvision=0.14.0=py39_cu117
  - tqdm=4.66.2=pyhd8ed1ab_0
  - typing_extensions=4.9.0=py39h06a4308_1
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xz=5.4.5=h5eee18b_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - anyio==4.3.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - astunparse==1.6.3
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - audioread==3.0.1
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - blinker==1.7.0
    - cachetools==5.5.0
    - cffi==1.16.0
    - chardet==5.2.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - coloredlogs==15.0.1
    - comm==0.2.1
    - configargparse==1.7
    - contourpy==1.2.0
    - cycler==0.12.1
    - cython==0.29.37
    - dash==2.15.0
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.8.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dnnlib==0.0.1
    - easydict==1.12
    - einops==0.7.0
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fastjsonschema==2.19.1
    - filelock==3.13.1
    - fire==0.5.0
    - flask==3.0.2
    - flatbuffers==1.12
    - fonttools==4.49.0
    - fqdn==1.5.1
    - freetype-py==2.4.0
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - ftfy==6.1.3
    - future==0.18.3
    - gast==0.4.0
    - google-auth==2.36.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - gputil==1.4.0
    - grpcio==1.60.1
    - h11==0.14.0
    - h5py==3.10.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.20.3
    - humanfriendly==10.0
    - hydra-core==1.3.2
    - idna==3.6
    - imageio==2.8.0
    - importlib-metadata==7.0.1
    - importlib-resources==6.1.1
    - iohandler==1.0.6
    - ipykernel==6.29.4
    - ipython==8.18.1
    - ipywidgets==8.1.2
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.19.1
    - jinja2==3.1.3
    - joblib==1.3.2
    - json5==0.9.24
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.1
    - jupyter-core==5.7.1
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.4
    - jupyter-server==2.13.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.1.5
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.4
    - jupyterlab-widgets==3.0.10
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.5
    - kornia==0.7.2
    - kornia-rs==0.1.2
    - libclang==18.1.1
    - libigl==2.5.1
    - librosa==0.7.2
    - lightning-utilities==0.10.1
    - llvmlite==0.42.0
    - lmdb==1.4.1
    - loguru==0.7.2
    - markdown==3.5.2
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.8.3
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mesh-to-sdf==0.0.15
    - mistune==3.0.2
    - ml-dtypes==0.3.2
    - mmcv==2.1.0
    - mmengine==0.10.3
    - mpmath==1.3.0
    - msgpack==1.0.7
    - msgpack-numpy==0.4.8
    - multidict==6.0.5
    - multipledispatch==1.0.0
    - mxnet-mkl==1.6.0
    - namex==0.0.7
    - nbclient==0.10.0
    - nbconvert==7.16.3
    - nbformat==5.9.2
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - ninja==1.11.1.1
    - notebook==7.1.2
    - notebook-shim==0.2.4
    - numba==0.59.0
    - numpy==1.23.1
    - oauthlib==3.2.2
    - ocnn==2.2.1
    - omegaconf==2.3.0
    - onnxruntime==1.18.0
    - open-clip-torch==2.24.0
    - open3d==0.18.0
    - opencv-python==4.9.0.80
    - opencv-python-headless==4.9.0.80
    - openexr==3.2.4
    - opt-einsum==3.3.0
    - optree==0.11.0
    - overrides==7.7.0
    - packaging==23.2
    - pandas==2.2.0
    - pandocfilters==1.5.1
    - parso==0.8.3
    - pathlib==1.0.1
    - pexpect==4.9.0
    - platformdirs==4.2.0
    - plotly==5.19.0
    - plyfile==1.0.3
    - pointnet2-ops==3.0.0
    - pooch==1.8.1
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.43
    - protobuf==4.25.3
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==16.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pycparser==2.21
    - pydeprecate==0.3.2
    - pyembree==0.1.12
    - pyexr==0.4.0
    - pyglet==2.0.10
    - pygments==2.17.2
    - pyhocon==0.3.61
    - pymatting==1.1.12
    - pymaxflow==1.3.0
    - pymcubes==0.1.4
    - pymesh2==0.3
    - pymeshlab==2023.12.post1
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.7
    - pyparsing==3.1.1
    - pyquaternion==0.9.9
    - pyrender==0.1.45
    - pyrr==0.10.3
    - python-dateutil==2.8.2
    - python-graphviz==0.8.4
    - python-json-logger==2.0.7
    - pytorch-lightning==1.6.1
    - pytz==2024.1
    - pyvirtualdisplay==3.0
    - pyvista==0.43.8
    - pywavelets==1.5.0
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - referencing==0.33.0
    - regex==2023.12.25
    - rembg==2.0.56
    - renderer==1.0.3
    - requests-oauthlib==2.0.0
    - resampy==0.4.2
    - retrying==1.3.4
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.7.1
    - rpds-py==0.18.0
    - rsa==4.9
    - rtree==1.3.0
    - safetensors==0.4.2
    - scikit-image==0.18.2
    - scikit-learn==0.24.2
    - scipy==1.12.0
    - scooby==0.10.0
    - send2trash==1.8.2
    - sentencepiece==0.1.99
    - setuptools==60.10.0
    - shapely==1.7.0
    - six==1.16.0
    - sniffio==1.3.1
    - soft-renderer==1.0.0
    - soundfile==0.12.1
    - soupsieve==2.5
    - stack-data==0.6.3
    - structlog==24.1.0
    - sympy==1.12
    - tenacity==8.2.3
    - tensorboard==2.16.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.36.0
    - terminado==0.18.1
    - tf-slim==1.1.0
    - threadpoolctl==3.3.0
    - tifffile==2024.2.12
    - timm==0.9.12
    - tinycss2==1.2.1
    - torchmetrics==1.3.1
    - tornado==6.4
    - traitlets==5.14.1
    - trimesh==3.23.5
    - types-python-dateutil==2.9.0.20240316
    - typing==3.7.4.3
    - tzdata==2024.1
    - uri-template==1.3.0
    - urllib3==2.2.1
    - vtk==9.3.0
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - werkzeug==3.0.1
    - wget==3.2
    - wheel==0.37.1
    - widgetsnbextension==4.0.10
    - wrapt==1.16.0
    - xvfbwrapper==0.2.9
    - xxhash==1.4.3
    - yapf==0.40.2
    - yarl==1.9.4
    - zipp==3.17.0
prefix: /public/home/chenxinyu/anaconda3/envs/DeepSketch2Wear
